apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: clusteroff
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  image: "borisshapa/clusteroff-db:latest"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/scripts/train.py"
  arguments:
    - "--config_path=configs/train.yml"
  sparkVersion: "3.4.1"
  deps:
    jars:
      - local:///opt/spark/jars/spark-cassandra-connector.jar
  sparkConf:
    spark.cassandra.connection.host: "cassandra"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    labels:
      version: 3.4.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "16g"
    labels:
      version: 3.4.1