apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: clusteroff
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  image: "borisshapa/clusteroff:latest"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/scripts/train.py"
  arguments:
    - "--config_path=configs/train.yml"
  sparkVersion: "3.4.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
  volumes:
    - name: "data"
      hostPath:
        path: "/clusteroff/data"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    labels:
      version: 3.4.1
    serviceAccount: spark
    volumeMounts:
      - name: data
        mountPath: /app/data
  executor:
    cores: 1
    instances: 1
    memory: "16g"
    labels:
      version: 3.4.1
    volumeMounts:
      - name: data
        mountPath: /app/data